//! Real daemon and MCP process evidence for every public budget-bearing tool.
//!
//! The retained report contains only bounded counters and digests; repository
//! source and process-local identities never leave the isolated fixture.

use std::{
    fs,
    io::{BufRead as _, BufReader, Read as _, Write as _},
    path::{Path, PathBuf},
    process::{Child, ChildStdin, Command, Stdio},
    sync::mpsc::{self, Receiver},
    thread::{self, JoinHandle},
    time::{Duration, Instant},
};

use rootlight_mcp_contract::accounting::estimate_tokens;
use serde::Serialize;
use serde_json::{Value, json};
use sha2::{Digest as _, Sha256};

const REPORT_SCHEMA: &str = "rootlight.mcp-budget-runtime/1";
const REPORT_ENV: &str = "ROOTLIGHT_BUDGET_RUNTIME_REPORT";
const SOURCE_REVISION_ENV: &str = "SOURCE_REVISION";
const MAX_REPORT_BYTES: usize = 128 * 1024;
const STARTUP_TIMEOUT: Duration = Duration::from_secs(15);
const RESPONSE_TIMEOUT: Duration = Duration::from_secs(30);
const SHUTDOWN_TIMEOUT: Duration = Duration::from_secs(10);
const MIN_RESPONSE_TOKEN_LIMIT: u64 = 100;
const MIN_CONTEXT_TOKEN_LIMIT: u64 = 500;
const EXPECTED_TOOLS: [&str; 14] = [
    "code.locate",
    "symbol.explain",
    "symbol.relationships",
    "flow.trace",
    "change.impact",
    "tests.select",
    "architecture.overview",
    "architecture.cycles",
    "code.dead",
    "history.compare",
    "plan.change",
    "context.pack",
    "source.read",
    "query.advanced",
];

#[test]
#[ignore = "retained real-process evidence is generated by its dedicated CI gate"]
fn all_budget_tools_enforce_hard_limits_across_daemon_and_mcp_processes() {
    let fixture = fixture_root();
    let fixture_sha256 = fixture_digest(&fixture);
    let isolated = tempfile::tempdir().expect("isolated process fixture is available");
    let repository_root = isolated.path().join("repository");
    copy_regular_tree(&fixture, &repository_root);
    let state_dir = isolated.path().join("state");
    let runtime_dir = isolated.path().join("runtime");
    let mut daemon = DaemonProcess::spawn(&state_dir, &runtime_dir);
    daemon.wait_until_ready(&runtime_dir);
    let mut mcp = McpProcess::spawn(&state_dir, &runtime_dir);

    let first = index_repository(&mut mcp, &repository_root, "index-v1");
    fs::OpenOptions::new()
        .append(true)
        .open(repository_root.join("src").join("lib.rs"))
        .and_then(|mut file| {
            file.write_all(
                b"\npub fn budget_added(value: usize) -> usize {\n    value.saturating_sub(1)\n}\n",
            )
        })
        .expect("fixture v2 mutation is written");
    let second = index_repository(&mut mcp, &repository_root, "index-v2");
    assert_eq!(first.repository_id, second.repository_id);
    assert_ne!(first.generation_id, second.generation_id);

    let entry = locate(&mut mcp, &second, "budget_entry", "setup-entry");
    let helper = locate(&mut mcp, &second, "budget_helper", "setup-helper");
    let cases = tool_cases(&first, &second, &entry, &helper);
    assert_eq!(
        cases.iter().map(|case| case.tool).collect::<Vec<_>>(),
        EXPECTED_TOOLS
    );

    let tokenizer = tiktoken_rs::o200k_base().expect("pinned o200k tokenizer initializes");
    let mut observations = Vec::with_capacity(cases.len());
    for (index, case) in cases.into_iter().enumerate() {
        let baseline = mcp.call(
            &format!("baseline-{index}"),
            case.tool,
            case.arguments.clone(),
        );
        let baseline_measurement = measure_success(case.tool, &baseline, &tokenizer);

        let (limited_arguments, trigger, limit, expected_error) = limited_arguments(
            case.tool,
            case.arguments,
            baseline_measurement.serialized_json_bytes,
        );
        let limited = mcp.call(&format!("limited-{index}"), case.tool, limited_arguments);
        let limited_measurement = measure_error(case.tool, &limited, expected_error, &tokenizer);
        observations.push(ToolBudgetObservation {
            tool: case.tool,
            trigger,
            limit,
            baseline: baseline_measurement,
            limited: limited_measurement,
        });
    }

    mcp.finish();
    daemon.finish();

    let report = RuntimeBudgetReport {
        schema: REPORT_SCHEMA,
        source_revision: source_revision(),
        fixture: FixtureEvidence {
            name: "budget-runtime-repository-v1",
            sha256: fixture_sha256,
            regular_files: regular_files(&fixture).len(),
        },
        process_boundary: ProcessBoundary {
            daemon: "rootlight-daemon supervised stdio",
            mcp: "rootlight-mcp JSON-RPC stdio",
            indexed_generations: 2,
        },
        tokenizer: TokenizerEvidence {
            name: "o200k_base",
            implementation: "tiktoken-rs",
            implementation_version: "0.12.0",
        },
        cases: observations,
    };
    validate_report(&report);
    if let Some(path) = std::env::var_os(REPORT_ENV) {
        write_report(Path::new(&path), &report);
    }
}

fn tool_cases(
    first: &IndexReceipt,
    second: &IndexReceipt,
    entry: &LocatedSymbol,
    helper: &LocatedSymbol,
) -> Vec<ToolCase> {
    let repository = || json!({"repository_id": second.repository_id});
    let generation = || Value::String(second.generation_id.clone());
    vec![
        ToolCase::new(
            "code.locate",
            json!({
                "repository": repository(),
                "generation": generation(),
                "query": "budget_entry",
                "search_modes": ["exact"],
                "max_results": 20
            }),
        ),
        ToolCase::new(
            "symbol.explain",
            json!({
                "repository": repository(),
                "generation": generation(),
                "symbol_ids": [entry.symbol_id, helper.symbol_id]
            }),
        ),
        ToolCase::new(
            "symbol.relationships",
            json!({
                "repository": repository(),
                "generation": generation(),
                "symbol_ids": [entry.symbol_id],
                "relations": ["calls", "references"],
                "direction": "both",
                "max_results": 20
            }),
        ),
        ToolCase::new(
            "flow.trace",
            json!({
                "repository": repository(),
                "generation": generation(),
                "from": {"symbol_id": entry.symbol_id},
                "relations": ["calls", "references"],
                "direction": "outbound",
                "max_depth": 3,
                "max_paths": 20
            }),
        ),
        ToolCase::new(
            "change.impact",
            json!({
                "repository": repository(),
                "generation": generation(),
                "change": {"symbol_ids": [entry.symbol_id, helper.symbol_id]},
                "max_depth": 3,
                "include_tests": true
            }),
        ),
        ToolCase::new(
            "tests.select",
            json!({
                "repository": repository(),
                "generation": generation(),
                "seeds": {"symbols": [entry.symbol_id, helper.symbol_id]}
            }),
        ),
        ToolCase::new(
            "architecture.overview",
            json!({
                "repository": repository(),
                "generation": generation()
            }),
        ),
        ToolCase::new(
            "architecture.cycles",
            json!({
                "repository": repository(),
                "generation": generation(),
                "projection": {"relations": ["calls"], "level": "symbol"},
                "max_cycles": 20
            }),
        ),
        ToolCase::new(
            "code.dead",
            json!({
                "repository": repository(),
                "generation": generation()
            }),
        ),
        ToolCase::new(
            "history.compare",
            json!({
                "repository": repository(),
                "base": first.generation_id,
                "head": second.generation_id,
                "max_results": 20
            }),
        ),
        ToolCase::new(
            "plan.change",
            json!({
                "repository": repository(),
                "generation": generation(),
                "objective": "bug_fix",
                "objective_text": "adjust the bounded budget entry path",
                "targets": [
                    {"symbol_id": entry.symbol_id},
                    {"symbol_id": helper.symbol_id}
                ]
            }),
        ),
        ToolCase::new(
            "context.pack",
            json!({
                "repository": repository(),
                "generation": generation(),
                "task": "explain and safely change the bounded budget entry path",
                "seeds": {"symbols": [entry.symbol_id, helper.symbol_id]},
                "token_budget": 2_000,
                "source_policy": "focused_snippets",
                "response_profile": "evidence"
            }),
        ),
        ToolCase::new(
            "source.read",
            json!({
                "repository": repository(),
                "generation": generation(),
                "references": [
                    {"source_ref": entry.source_ref},
                    {"source_ref": helper.source_ref}
                ],
                "include_line_numbers": true,
                "encoding": "utf8_lossless_when_valid"
            }),
        ),
        ToolCase::new(
            "query.advanced",
            json!({
                "repository": repository(),
                "generation": generation(),
                "query": {"op": "scan", "entity": "function"},
                "max_results": 100,
                "max_depth": 5,
                "cost_limit": 10_000_000
            }),
        ),
    ]
}

fn limited_arguments(
    tool: &str,
    mut arguments: Value,
    baseline_json_bytes: u64,
) -> (Value, &'static str, u64, &'static str) {
    if tool == "context.pack" {
        arguments["token_budget"] = json!(MIN_CONTEXT_TOKEN_LIMIT);
        return (
            arguments,
            "token_budget",
            MIN_CONTEXT_TOKEN_LIMIT,
            "BUDGET_EXCEEDED",
        );
    }
    if tool == "query.advanced" {
        arguments["cost_limit"] = json!(1);
        return (arguments, "cost_limit", 1, "COST_LIMIT");
    }
    let limit = baseline_json_bytes
        .saturating_sub(1)
        .max(MIN_RESPONSE_TOKEN_LIMIT);
    assert!(
        limit <= 16_000,
        "{tool} baseline exceeds the public max_tokens schema ceiling"
    );
    arguments
        .as_object_mut()
        .expect("tool arguments are objects")
        .insert("budget".to_owned(), json!({"max_tokens": limit}));
    (arguments, "budget.max_tokens", limit, "BUDGET_EXCEEDED")
}

fn measure_success(
    tool: &str,
    response: &Value,
    tokenizer: &tiktoken_rs::CoreBPE,
) -> SuccessMeasurement {
    assert_ne!(
        response["result"]["isError"], true,
        "{tool} baseline returned a public error: {response:#}"
    );
    let structured = &response["result"]["structuredContent"];
    assert!(
        structured.is_object(),
        "{tool} baseline omitted structured content"
    );
    let serialized = serde_json::to_vec(structured).expect("structured content serializes");
    let serialized_json_bytes =
        u64::try_from(serialized.len()).expect("serialized response length fits");
    let public_estimated_tokens = estimate_tokens(serialized.len());
    assert_eq!(
        structured["usage"]["json_bytes"].as_u64(),
        Some(serialized_json_bytes),
        "{tool} did not report authoritative serialized JSON bytes"
    );
    assert_eq!(
        structured["usage"]["estimated_tokens"].as_u64(),
        Some(public_estimated_tokens),
        "{tool} did not report the public deterministic estimate"
    );
    SuccessMeasurement {
        serialized_json_bytes,
        public_estimated_tokens,
        actual_o200k_tokens: actual_tokens(&serialized, tokenizer),
        structured_sha256: sha256_hex(&serialized),
    }
}

fn measure_error(
    tool: &str,
    response: &Value,
    expected_code: &'static str,
    tokenizer: &tiktoken_rs::CoreBPE,
) -> LimitMeasurement {
    assert_eq!(
        response["result"]["isError"], true,
        "{tool} hard limit did not return a checked public error: {response:#}"
    );
    let structured = &response["result"]["structuredContent"];
    assert_eq!(
        structured["error"]["code"], expected_code,
        "{tool} returned the wrong hard-limit error: {response:#}"
    );
    let serialized = serde_json::to_vec(structured).expect("structured error serializes");
    LimitMeasurement {
        error_code: expected_code,
        serialized_json_bytes: u64::try_from(serialized.len())
            .expect("serialized error length fits"),
        public_estimated_tokens: estimate_tokens(serialized.len()),
        actual_o200k_tokens: actual_tokens(&serialized, tokenizer),
        structured_sha256: sha256_hex(&serialized),
    }
}

fn actual_tokens(input: &[u8], tokenizer: &tiktoken_rs::CoreBPE) -> u64 {
    let text = std::str::from_utf8(input).expect("canonical JSON is UTF-8");
    u64::try_from(tokenizer.encode_with_special_tokens(text).len())
        .expect("token count fits unsigned evidence")
}

fn validate_report(report: &RuntimeBudgetReport) {
    assert!(valid_revision(&report.source_revision));
    assert_eq!(report.cases.len(), EXPECTED_TOOLS.len());
    assert_eq!(
        report
            .cases
            .iter()
            .map(|case| case.tool)
            .collect::<Vec<_>>(),
        EXPECTED_TOOLS
    );
    assert!(
        report.cases.iter().all(|case| {
            case.baseline.serialized_json_bytes > 0
                && case.baseline.public_estimated_tokens
                    == estimate_tokens(
                        usize::try_from(case.baseline.serialized_json_bytes)
                            .expect("response bytes fit usize"),
                    )
                && case.baseline.actual_o200k_tokens > 0
                && case.baseline.structured_sha256.len() == 64
                && case.limited.serialized_json_bytes > 0
                && case.limited.public_estimated_tokens
                    == estimate_tokens(
                        usize::try_from(case.limited.serialized_json_bytes)
                            .expect("error bytes fit usize"),
                    )
                && case.limited.actual_o200k_tokens > 0
                && case.limited.structured_sha256.len() == 64
        }),
        "every runtime case must retain measured byte and token evidence"
    );
}

fn write_report(path: &Path, report: &RuntimeBudgetReport) {
    let mut encoded = serde_json::to_vec_pretty(report).expect("runtime report serializes");
    encoded.push(b'\n');
    assert!(
        encoded.len() <= MAX_REPORT_BYTES,
        "runtime report exceeds its retained evidence ceiling"
    );
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent).expect("runtime report directory is created");
    }
    fs::write(path, encoded).expect("runtime report is written");
}

fn source_revision() -> String {
    let revision = std::env::var(SOURCE_REVISION_ENV).unwrap_or_else(|_| {
        let output = Command::new("git")
            .args(["rev-parse", "HEAD"])
            .current_dir(Path::new(env!("CARGO_MANIFEST_DIR")).join("../.."))
            .output()
            .expect("git source revision command starts");
        assert!(
            output.status.success(),
            "git source revision command succeeds"
        );
        String::from_utf8(output.stdout)
            .expect("git source revision is UTF-8")
            .trim()
            .to_owned()
    });
    assert!(valid_revision(&revision), "source revision is canonical");
    revision
}

fn valid_revision(revision: &str) -> bool {
    matches!(revision.len(), 40 | 64)
        && revision
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn fixture_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("tests/fixtures/mcp/budget-runtime/repository")
}

fn regular_files(root: &Path) -> Vec<PathBuf> {
    fn walk(root: &Path, directory: &Path, output: &mut Vec<PathBuf>) {
        let mut entries = fs::read_dir(directory)
            .expect("fixture directory reads")
            .collect::<Result<Vec<_>, _>>()
            .expect("fixture entries read");
        entries.sort_by_key(std::fs::DirEntry::file_name);
        for entry in entries {
            let kind = entry.file_type().expect("fixture file type reads");
            assert!(!kind.is_symlink(), "fixture cannot contain symbolic links");
            if kind.is_dir() {
                walk(root, &entry.path(), output);
            } else if kind.is_file() {
                output.push(
                    entry
                        .path()
                        .strip_prefix(root)
                        .expect("fixture path stays below root")
                        .to_path_buf(),
                );
            }
        }
    }
    let mut output = Vec::new();
    walk(root, root, &mut output);
    output
}

fn fixture_digest(root: &Path) -> String {
    let mut digest = Sha256::new();
    for relative in regular_files(root) {
        let normalized = relative.to_string_lossy().replace('\\', "/");
        let bytes = fs::read(root.join(&relative)).expect("fixture file reads");
        digest.update(normalized.as_bytes());
        digest.update([0]);
        digest.update(
            u64::try_from(bytes.len())
                .expect("fixture length fits")
                .to_le_bytes(),
        );
        digest.update(&bytes);
    }
    sha256_hex(&digest.finalize())
}

fn copy_regular_tree(source: &Path, destination: &Path) {
    fs::create_dir_all(destination).expect("fixture destination is created");
    for relative in regular_files(source) {
        let target = destination.join(&relative);
        fs::create_dir_all(target.parent().expect("fixture file has a parent"))
            .expect("fixture parent directory is created");
        fs::copy(source.join(&relative), target).expect("fixture file is copied");
    }
}

fn sha256_hex(input: &[u8]) -> String {
    use std::fmt::Write as _;

    let digest = Sha256::digest(input);
    let mut encoded = String::with_capacity(64);
    for byte in digest {
        write!(encoded, "{byte:02x}").expect("writing to a string cannot fail");
    }
    encoded
}

fn index_repository(mcp: &mut McpProcess, root: &Path, id: &str) -> IndexReceipt {
    let response = mcp.call(
        id,
        "repo.index",
        json!({"root": root, "mode": "auto", "detached": false}),
    );
    assert_success(&response, "repo.index");
    let data = &response["result"]["structuredContent"]["data"];
    let repository_id = required_string(&data["repository_id"], "repository identity");
    let operation_id = required_string(&data["operation_id"], "operation identity");
    let generation_id = if data["state"] == "published" {
        required_string(&data["published_generation"], "published generation")
    } else {
        wait_for_publication(mcp, &operation_id)
    };
    IndexReceipt {
        repository_id,
        generation_id,
    }
}

fn wait_for_publication(mcp: &mut McpProcess, operation_id: &str) -> String {
    for attempt in 0..30 {
        let response = mcp.call(
            &format!("operation-{operation_id}-{attempt}"),
            "operation.status",
            json!({"operation_id": operation_id, "wait_ms": 1_000}),
        );
        assert_success(&response, "operation.status");
        let data = &response["result"]["structuredContent"]["data"];
        match data["operation"]["state"].as_str() {
            Some("published") => {
                return required_string(&data["published_generation"], "published generation");
            }
            Some("failed" | "cancelled") => {
                panic!("fixture indexing terminated without publication: {response:#}")
            }
            _ => {}
        }
    }
    panic!("fixture indexing did not publish within the bounded wait");
}

fn locate(mcp: &mut McpProcess, index: &IndexReceipt, query: &str, id: &str) -> LocatedSymbol {
    let response = mcp.call(
        id,
        "code.locate",
        json!({
            "repository": {"repository_id": index.repository_id},
            "generation": index.generation_id,
            "query": query,
            "search_modes": ["exact"],
            "max_results": 2
        }),
    );
    assert_success(&response, "code.locate");
    let matches = response["result"]["structuredContent"]["data"]["matches"]
        .as_array()
        .expect("code.locate returns matches");
    assert_eq!(matches.len(), 1, "setup locate returns one exact symbol");
    LocatedSymbol {
        symbol_id: required_string(&matches[0]["symbol_id"], "symbol identity"),
        source_ref: matches[0]["source_ref"].clone(),
    }
}

fn assert_success(response: &Value, tool: &str) {
    assert_ne!(
        response["result"]["isError"], true,
        "{tool} returned a public error: {response:#}"
    );
    assert!(
        response["result"]["structuredContent"].is_object(),
        "{tool} omitted structured content: {response:#}"
    );
}

fn required_string(value: &Value, field: &str) -> String {
    value
        .as_str()
        .unwrap_or_else(|| panic!("{field} is absent: {value:#}"))
        .to_owned()
}

fn tool_call(id: &str, tool: &str, arguments: Value) -> Value {
    json!({
        "jsonrpc": "2.0",
        "id": id,
        "method": "tools/call",
        "params": {"name": tool, "arguments": arguments}
    })
}

fn daemon_binary() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_rootlight-mcp"))
        .parent()
        .expect("MCP binary has a profile directory")
        .join(format!("rootlight-daemon{}", std::env::consts::EXE_SUFFIX))
}

struct DaemonProcess {
    child: Option<Child>,
    input: Option<ChildStdin>,
}

impl DaemonProcess {
    fn spawn(state_dir: &Path, runtime_dir: &Path) -> Self {
        let binary = daemon_binary();
        assert!(
            binary.is_file(),
            "budget process evidence requires a prebuilt daemon at {binary:?}"
        );
        let mut child = Command::new(binary)
            .arg("--supervised-stdio")
            .env("ROOTLIGHT_STATE_DIR", state_dir)
            .env("ROOTLIGHT_RUNTIME_DIR", runtime_dir)
            .stdin(Stdio::piped())
            .stdout(Stdio::null())
            .stderr(Stdio::piped())
            .spawn()
            .expect("isolated daemon process starts");
        let input = child.stdin.take().expect("daemon stdin is piped");
        Self {
            child: Some(child),
            input: Some(input),
        }
    }

    fn wait_until_ready(&mut self, runtime_dir: &Path) {
        let deadline = Instant::now() + STARTUP_TIMEOUT;
        let discovery = runtime_dir.join("daemon.json");
        while Instant::now() < deadline {
            if discovery.is_file() {
                return;
            }
            if self
                .child
                .as_mut()
                .expect("daemon child is retained")
                .try_wait()
                .expect("daemon status is readable")
                .is_some()
            {
                panic!("daemon exited before publishing discovery");
            }
            thread::sleep(Duration::from_millis(25));
        }
        panic!("daemon did not publish discovery within the startup bound");
    }

    fn finish(&mut self) {
        self.input.take();
        let child = self.child.as_mut().expect("daemon child is retained");
        let status = wait_for_exit(child, SHUTDOWN_TIMEOUT);
        let mut stderr = String::new();
        child
            .stderr
            .take()
            .expect("daemon stderr is piped")
            .read_to_string(&mut stderr)
            .expect("daemon stderr reads");
        assert!(
            status.success(),
            "daemon process exits successfully: {stderr}"
        );
        self.child.take();
    }
}

impl Drop for DaemonProcess {
    fn drop(&mut self) {
        self.input.take();
        terminate(&mut self.child);
    }
}

struct McpProcess {
    child: Option<Child>,
    input: Option<ChildStdin>,
    responses: Receiver<String>,
    reader: Option<JoinHandle<()>>,
}

impl McpProcess {
    fn spawn(state_dir: &Path, runtime_dir: &Path) -> Self {
        let mut child = Command::new(env!("CARGO_BIN_EXE_rootlight-mcp"))
            .env("ROOTLIGHT_STATE_DIR", state_dir)
            .env("ROOTLIGHT_RUNTIME_DIR", runtime_dir)
            .env("ROOTLIGHT_MCP_PROFILE", "developer")
            .env("ROOTLIGHT_MCP_PROFILE_CEILING", "developer")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("MCP fixture process starts");
        let output = child.stdout.take().expect("MCP stdout is piped");
        let (responses_tx, responses) = mpsc::sync_channel(64);
        let reader = thread::spawn(move || {
            for line in BufReader::new(output).lines() {
                let Ok(line) = line else {
                    return;
                };
                if responses_tx.send(line).is_err() {
                    return;
                }
            }
        });
        let mut process = Self {
            input: child.stdin.take(),
            child: Some(child),
            responses,
            reader: Some(reader),
        };
        process.write(&json!({
            "jsonrpc": "2.0",
            "id": "initialize",
            "method": "initialize",
            "params": {
                "protocolVersion": "2025-11-25",
                "capabilities": {},
                "clientInfo": {"name": "budget-process", "version": "1.0"},
                "initializationOptions": {"rootlight_exposure_profile": "developer"}
            }
        }));
        assert_eq!(process.read()["id"], "initialize");
        process.write(&json!({
            "jsonrpc": "2.0",
            "method": "notifications/initialized",
            "params": {}
        }));
        process
    }

    fn call(&mut self, id: &str, tool: &str, arguments: Value) -> Value {
        self.write(&tool_call(id, tool, arguments));
        let response = self.read();
        assert_eq!(response["id"], id, "MCP response identity differs");
        response
    }

    fn write(&mut self, message: &Value) {
        let input = self.input.as_mut().expect("MCP stdin is retained");
        serde_json::to_writer(&mut *input, message).expect("MCP request serializes");
        input.write_all(b"\n").expect("MCP request terminates");
        input.flush().expect("MCP request flushes");
    }

    fn read(&self) -> Value {
        let line = self
            .responses
            .recv_timeout(RESPONSE_TIMEOUT)
            .expect("MCP response arrives within the bound");
        serde_json::from_str(&line).expect("MCP response is valid JSON")
    }

    fn finish(&mut self) {
        self.input.take();
        let child = self.child.as_mut().expect("MCP child is retained");
        let status = wait_for_exit(child, SHUTDOWN_TIMEOUT);
        let mut stderr = String::new();
        child
            .stderr
            .take()
            .expect("MCP stderr is piped")
            .read_to_string(&mut stderr)
            .expect("MCP stderr reads");
        assert!(status.success(), "MCP process exits successfully: {stderr}");
        assert!(stderr.is_empty(), "MCP process wrote stderr: {stderr}");
        self.child.take();
        self.reader
            .take()
            .expect("MCP reader is retained")
            .join()
            .expect("MCP reader thread joins");
    }
}

impl Drop for McpProcess {
    fn drop(&mut self) {
        self.input.take();
        terminate(&mut self.child);
        if let Some(reader) = self.reader.take() {
            let _ = reader.join();
        }
    }
}

fn wait_for_exit(child: &mut Child, timeout: Duration) -> std::process::ExitStatus {
    let deadline = Instant::now() + timeout;
    while Instant::now() < deadline {
        if let Some(status) = child.try_wait().expect("child status is readable") {
            return status;
        }
        thread::sleep(Duration::from_millis(25));
    }
    child.kill().expect("timed-out child is terminated");
    child.wait().expect("terminated child is reaped")
}

fn terminate(child: &mut Option<Child>) {
    if let Some(mut child) = child.take() {
        if child.try_wait().ok().flatten().is_none() {
            let _ = child.kill();
        }
        let _ = child.wait();
    }
}

struct ToolCase {
    tool: &'static str,
    arguments: Value,
}

impl ToolCase {
    fn new(tool: &'static str, arguments: Value) -> Self {
        Self { tool, arguments }
    }
}

struct IndexReceipt {
    repository_id: String,
    generation_id: String,
}

struct LocatedSymbol {
    symbol_id: String,
    source_ref: Value,
}

#[derive(Serialize)]
struct RuntimeBudgetReport {
    schema: &'static str,
    source_revision: String,
    fixture: FixtureEvidence,
    process_boundary: ProcessBoundary,
    tokenizer: TokenizerEvidence,
    cases: Vec<ToolBudgetObservation>,
}

#[derive(Serialize)]
struct FixtureEvidence {
    name: &'static str,
    sha256: String,
    regular_files: usize,
}

#[derive(Serialize)]
struct ProcessBoundary {
    daemon: &'static str,
    mcp: &'static str,
    indexed_generations: u8,
}

#[derive(Serialize)]
struct TokenizerEvidence {
    name: &'static str,
    implementation: &'static str,
    implementation_version: &'static str,
}

#[derive(Serialize)]
struct ToolBudgetObservation {
    tool: &'static str,
    trigger: &'static str,
    limit: u64,
    baseline: SuccessMeasurement,
    limited: LimitMeasurement,
}

#[derive(Serialize)]
struct SuccessMeasurement {
    serialized_json_bytes: u64,
    public_estimated_tokens: u64,
    actual_o200k_tokens: u64,
    structured_sha256: String,
}

#[derive(Serialize)]
struct LimitMeasurement {
    error_code: &'static str,
    serialized_json_bytes: u64,
    public_estimated_tokens: u64,
    actual_o200k_tokens: u64,
    structured_sha256: String,
}
