[package]
name = "rootlight-sandbox"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
  "Win32_Security_Cryptography",
  "Win32_Security_Isolation",
  "Win32_System_LibraryLoader",
  "Win32_System_SystemServices",
] }

[lints.rust]
missing_docs = "warn"
unsafe_code = "deny"
unreachable_pub = "warn"

[lints.clippy]
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_sign_loss = "warn"
dbg_macro = "warn"
missing_errors_doc = "warn"
missing_panics_doc = "warn"
todo = "warn"
undocumented_unsafe_blocks = "warn"
