[package]
name = "rootlight-launcher"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
fs2.workspace = true
rootlight-build = { path = "../../crates/rootlight-build" }
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[target.'cfg(windows)'.dependencies]
nt-token.workspace = true
windows.workspace = true
windows-permissions.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
