//! Immutable per-file and whole-project adapter requests.
//!
//! Checked snapshots bind concrete VFS bytes to full-file repository generation
//! references before any adapter can observe individual or aggregate inputs.

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt,
    sync::Arc,
};

use rootlight_ids::{ContentHash, content_hash};
use rootlight_ir::{AnalysisTier, BuildContextIdentity, SourceRef, SourceSpan};
use rootlight_vfs::{RelativePath, SourceSnapshot};

use crate::{
    descriptor::{EncodingId, LanguageId, validated_label},
    error::{LabelError, LabelField, LabelViolation, RequestError, ResourceKind, SnapshotError},
    limits::AnalysisLimits,
};

const MAX_PROJECT_ID_BYTES: usize = 1_024;
const MAX_TRANSFORMATION_ID_BYTES: usize = 128;
const GENERATED_ORIGIN_RULE_VERSION: &str = "rootlight.generated-origin.v1";

/// Canonical identity for one project analysis unit.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct AnalysisUnitId(String);

impl AnalysisUnitId {
    /// Creates a bounded source-free analysis-unit identity.
    ///
    /// # Errors
    ///
    /// Returns [`LabelError`] when the identity is empty, oversized, or
    /// contains bytes outside the canonical label grammar.
    pub fn new(value: &str) -> Result<Self, LabelError> {
        validated_project_label(LabelField::AnalysisUnit, value, MAX_PROJECT_ID_BYTES).map(Self)
    }

    /// Returns the canonical identity text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Canonical identity for one selected build target.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BuildTargetId(String);

impl BuildTargetId {
    /// Creates a bounded source-free build-target identity.
    ///
    /// # Errors
    ///
    /// Returns [`LabelError`] when the identity is empty, oversized, or
    /// contains bytes outside the canonical label grammar.
    pub fn new(value: &str) -> Result<Self, LabelError> {
        validated_project_label(LabelField::BuildTarget, value, MAX_PROJECT_ID_BYTES).map(Self)
    }

    /// Returns the canonical identity text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Stable identity of a generated-source transformation.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct TransformationId(String);

impl TransformationId {
    /// Creates a bounded transformation identity.
    ///
    /// # Errors
    ///
    /// Returns [`LabelError`] when the identity violates the canonical label
    /// grammar.
    pub fn new(value: &str) -> Result<Self, LabelError> {
        validated_label(
            LabelField::Transformation,
            value,
            MAX_TRANSFORMATION_ID_BYTES,
        )
        .map(Self)
    }

    /// Returns the canonical identity text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// One project-relative mapping from generated bytes to their origin.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedOriginMapping {
    generated: SourceSpan,
    origin_path: RelativePath,
    origin: SourceSpan,
    transformation: TransformationId,
    generator_digest: Option<ContentHash>,
}

impl GeneratedOriginMapping {
    /// Creates a mapping whose source ownership and ranges are request-validated.
    #[must_use]
    pub fn new(
        generated: SourceSpan,
        origin_path: RelativePath,
        origin: SourceSpan,
        transformation: TransformationId,
        generator_digest: Option<ContentHash>,
    ) -> Self {
        Self {
            generated,
            origin_path,
            origin,
            transformation,
            generator_digest,
        }
    }

    /// Returns the mapped generated-source span.
    #[must_use]
    pub const fn generated(&self) -> SourceSpan {
        self.generated
    }

    /// Returns the canonical repository-relative origin path.
    #[must_use]
    pub const fn origin_path(&self) -> &RelativePath {
        &self.origin_path
    }

    /// Returns the origin byte span.
    #[must_use]
    pub const fn origin(&self) -> SourceSpan {
        self.origin
    }

    /// Returns the transformation identity.
    #[must_use]
    pub const fn transformation(&self) -> &TransformationId {
        &self.transformation
    }

    /// Returns the optional generator binary or configuration digest.
    #[must_use]
    pub const fn generator_digest(&self) -> Option<ContentHash> {
        self.generator_digest
    }

    /// Returns the canonical provenance rule for the mapping transformation.
    ///
    /// The normalized source-mapping record has no transformation fields of
    /// its own, so adapters retain this bounded identity in its referenced
    /// provenance record instead of dropping generator evidence.
    #[must_use]
    pub fn provenance_rule(&self) -> String {
        match self.generator_digest {
            Some(digest) => format!(
                "{GENERATED_ORIGIN_RULE_VERSION}:{}:{digest}",
                self.transformation.as_str()
            ),
            None => format!(
                "{GENERATED_ORIGIN_RULE_VERSION}:{}:none",
                self.transformation.as_str()
            ),
        }
    }

    fn accounted_bytes(&self) -> Result<usize, RequestError> {
        self.origin_path
            .identity_bytes()
            .len()
            .checked_add(self.transformation.as_str().len())
            .and_then(|bytes| bytes.checked_add(4 * size_of::<u64>()))
            .and_then(|bytes| {
                bytes.checked_add(
                    self.generator_digest
                        .map_or(0, |digest| digest.as_bytes().len()),
                )
            })
            .ok_or(RequestError::ProjectAccountingOverflow)
    }
}

/// One immutable generation-bound input to a project analyzer.
#[derive(Debug, Clone)]
pub struct ProjectSourceInput<'a> {
    source: GenerationBoundSnapshot<'a>,
    language: LanguageId,
    encoding: EncodingId,
    generated: bool,
    origins: Arc<Vec<GeneratedOriginMapping>>,
}

impl<'a> ProjectSourceInput<'a> {
    /// Creates a project source input; aggregate request construction validates it.
    #[must_use]
    pub fn new(
        source: GenerationBoundSnapshot<'a>,
        language: LanguageId,
        encoding: EncodingId,
        generated: bool,
        origins: Vec<GeneratedOriginMapping>,
    ) -> Self {
        Self {
            source,
            language,
            encoding,
            generated,
            origins: Arc::new(origins),
        }
    }

    /// Returns the immutable generation-bound source.
    #[must_use]
    pub const fn source(&self) -> &GenerationBoundSnapshot<'a> {
        &self.source
    }

    /// Returns the source language identity.
    #[must_use]
    pub const fn language(&self) -> &LanguageId {
        &self.language
    }

    /// Returns the declared source encoding.
    #[must_use]
    pub const fn encoding(&self) -> &EncodingId {
        &self.encoding
    }

    /// Reports whether the repository classified this source as generated.
    #[must_use]
    pub const fn is_generated(&self) -> bool {
        self.generated
    }

    /// Returns sorted, disjoint project-relative generated-origin mappings.
    #[must_use]
    pub fn origins(&self) -> &[GeneratedOriginMapping] {
        self.origins.as_slice()
    }
}

/// One bounded transactional request over a complete project analysis unit.
#[derive(Debug, Clone)]
pub struct ProjectAnalysisRequest<'a> {
    analysis_unit: AnalysisUnitId,
    build_target: BuildTargetId,
    build_context: BuildContextIdentity,
    configuration_digest: ContentHash,
    context_manifest: &'a [u8],
    inputs: Arc<Vec<ProjectSourceInput<'a>>>,
    anchor: SourceRef,
    requested_tier: AnalysisTier,
    total_source_bytes: usize,
    limits: &'a AnalysisLimits,
}

impl<'a> ProjectAnalysisRequest<'a> {
    /// Creates a canonical multi-file project request.
    ///
    /// Inputs must be strictly sorted by [`RelativePath::identity_bytes`] and
    /// belong to one repository generation. Source identity, all mapping
    /// ranges, and aggregate project quotas are validated before an analyzer
    /// can observe the request.
    ///
    /// # Errors
    ///
    /// Returns [`RequestError`] for disabled project admission, empty or
    /// noncanonical inputs, inconsistent generation identity, invalid
    /// generated-origin mappings, accounting overflow, or any exceeded
    /// per-file or aggregate limit.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        analysis_unit: AnalysisUnitId,
        build_target: BuildTargetId,
        build_context: BuildContextIdentity,
        configuration_digest: ContentHash,
        context_manifest: &'a [u8],
        inputs: Vec<ProjectSourceInput<'a>>,
        requested_tier: AnalysisTier,
        limits: &'a AnalysisLimits,
    ) -> Result<Self, RequestError> {
        let project_limits = limits
            .project()
            .ok_or(RequestError::ProjectAnalysisDisabled)?;
        let anchor = inputs
            .first()
            .ok_or(RequestError::EmptyProject)?
            .source()
            .source_ref()
            .clone();
        require_project_limit(
            ResourceKind::ProjectFiles,
            inputs.len(),
            project_limits.max_files(),
        )?;
        require_project_limit(
            ResourceKind::ProjectContextBytes,
            context_manifest.len(),
            project_limits.max_context_bytes(),
        )?;
        if content_hash(context_manifest) != configuration_digest {
            return Err(RequestError::ProjectConfigurationDigestMismatch);
        }
        require_project_limit(
            ResourceKind::AnalysisUnitBytes,
            analysis_unit.as_str().len(),
            project_limits.max_analysis_unit_bytes(),
        )?;
        require_project_limit(
            ResourceKind::BuildTargetBytes,
            build_target.as_str().len(),
            project_limits.max_build_target_bytes(),
        )?;

        let mut total_source_bytes = 0_usize;
        let mut total_mappings = 0_usize;
        let mut total_mapping_bytes = 0_usize;
        let mut previous_path: Option<&[u8]> = None;
        let mut files = BTreeSet::new();
        let mut paths = BTreeMap::new();
        for (index, input) in inputs.iter().enumerate() {
            let source = input.source().source_ref();
            if source.repository() != anchor.repository() {
                return Err(RequestError::ProjectRepositoryMismatch { index });
            }
            if source.generation() != anchor.generation() {
                return Err(RequestError::ProjectGenerationMismatch { index });
            }
            if !files.insert(source.span().file()) {
                return Err(RequestError::DuplicateProjectFile { index });
            }
            let path = input.source().path().identity_bytes();
            if previous_path.is_some_and(|previous| previous >= path) {
                return Err(RequestError::ProjectPathOrder { index });
            }
            previous_path = Some(path);
            paths.insert(path, index);
            validate_source_size(input.source(), limits)?;
            total_source_bytes = total_source_bytes
                .checked_add(input.source().bytes().len())
                .ok_or(RequestError::ProjectAccountingOverflow)?;
            if !input.generated && !input.origins.is_empty() {
                return Err(RequestError::OriginsRequireGeneratedSource { index });
            }
            total_mappings = total_mappings
                .checked_add(input.origins.len())
                .ok_or(RequestError::ProjectAccountingOverflow)?;
            for mapping in input.origins.iter() {
                total_mapping_bytes = total_mapping_bytes
                    .checked_add(mapping.accounted_bytes()?)
                    .ok_or(RequestError::ProjectAccountingOverflow)?;
            }
        }

        require_project_limit(
            ResourceKind::ProjectSourceBytes,
            total_source_bytes,
            project_limits.max_total_source_bytes(),
        )?;
        require_project_limit(
            ResourceKind::GeneratedMappings,
            total_mappings,
            project_limits.max_generated_mappings(),
        )?;
        require_project_limit(
            ResourceKind::GeneratedMappingBytes,
            total_mapping_bytes,
            project_limits.max_generated_mapping_bytes(),
        )?;
        validate_project_mappings(&inputs, &paths)?;

        Ok(Self {
            analysis_unit,
            build_target,
            build_context,
            configuration_digest,
            context_manifest,
            inputs: Arc::new(inputs),
            anchor,
            requested_tier,
            total_source_bytes,
            limits,
        })
    }

    /// Returns the canonical analysis-unit identity.
    #[must_use]
    pub const fn analysis_unit(&self) -> &AnalysisUnitId {
        &self.analysis_unit
    }

    /// Returns the selected canonical build target.
    #[must_use]
    pub const fn build_target(&self) -> &BuildTargetId {
        &self.build_target
    }

    /// Returns the exact build-context identity.
    #[must_use]
    pub const fn build_context(&self) -> BuildContextIdentity {
        self.build_context
    }

    /// Returns the canonical project configuration digest.
    #[must_use]
    pub const fn configuration_digest(&self) -> ContentHash {
        self.configuration_digest
    }

    /// Returns the bounded canonical build-context manifest.
    #[must_use]
    pub const fn context_manifest(&self) -> &[u8] {
        self.context_manifest
    }

    /// Returns canonically ordered generation-bound source inputs.
    #[must_use]
    pub fn inputs(&self) -> &[ProjectSourceInput<'a>] {
        self.inputs.as_slice()
    }

    /// Returns the highest analysis tier requested by the caller.
    #[must_use]
    pub const fn requested_tier(&self) -> AnalysisTier {
        self.requested_tier
    }

    /// Returns aggregate admitted source bytes.
    #[must_use]
    pub const fn total_source_bytes(&self) -> usize {
        self.total_source_bytes
    }

    /// Returns the repository-generation anchor shared by every input.
    #[must_use]
    pub(crate) const fn anchor(&self) -> &SourceRef {
        &self.anchor
    }

    /// Returns explicit per-file, aggregate, stream, and IR limits.
    #[must_use]
    pub const fn limits(&self) -> &AnalysisLimits {
        self.limits
    }
}

/// A checked full-file source range with an embedded language identity.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IncludedRange {
    span: SourceSpan,
    language: LanguageId,
}

impl IncludedRange {
    /// Creates an included range; its owning request validates file and bounds.
    #[must_use]
    pub const fn new(span: SourceSpan, language: LanguageId) -> Self {
        Self { span, language }
    }

    /// Returns the included source span.
    #[must_use]
    pub const fn span(&self) -> SourceSpan {
        self.span
    }

    /// Returns the language active in the included range.
    #[must_use]
    pub const fn language(&self) -> &LanguageId {
        &self.language
    }
}

/// Concrete immutable VFS bytes bound to one full-file generation reference.
#[derive(Clone)]
pub struct GenerationBoundSnapshot<'a> {
    snapshot: &'a SourceSnapshot,
    source: SourceRef,
}

impl<'a> GenerationBoundSnapshot<'a> {
    /// Binds a VFS snapshot to an exact full-file [`SourceRef`].
    ///
    /// # Errors
    ///
    /// Returns [`SnapshotError`] when file, hash, or full-file span identity
    /// differs from the captured bytes.
    pub fn new(snapshot: &'a SourceSnapshot, source: &SourceRef) -> Result<Self, SnapshotError> {
        if snapshot.file() != source.span().file() {
            return Err(SnapshotError::FileMismatch);
        }
        if snapshot.content_hash() != source.content_hash() {
            return Err(SnapshotError::ContentHashMismatch);
        }
        let byte_length =
            u64::try_from(snapshot.content().len()).map_err(|_| SnapshotError::LengthOverflow)?;
        if source.span().start_byte() != 0
            || source.span().end_byte() != byte_length
            || snapshot.metadata().length != byte_length
        {
            return Err(SnapshotError::NotFullFile);
        }
        Ok(Self {
            snapshot,
            source: source.clone(),
        })
    }

    /// Returns the immutable captured source bytes.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        self.snapshot.content()
    }

    /// Returns the canonical repository-relative path.
    #[must_use]
    pub const fn path(&self) -> &RelativePath {
        self.snapshot.path()
    }

    /// Returns the exact full-file generation reference.
    #[must_use]
    pub const fn source_ref(&self) -> &SourceRef {
        &self.source
    }

    /// Returns the underlying immutable VFS snapshot.
    #[must_use]
    pub const fn snapshot(&self) -> &SourceSnapshot {
        self.snapshot
    }
}

impl fmt::Debug for GenerationBoundSnapshot<'_> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("GenerationBoundSnapshot")
            .field("source", &self.source)
            .field("byte_length", &self.snapshot.content().len())
            .finish()
    }
}

/// One bounded synchronous parse request for immutable source bytes.
#[derive(Debug, Clone)]
pub struct ParseRequest<'a> {
    source: GenerationBoundSnapshot<'a>,
    language: LanguageId,
    encoding: EncodingId,
    included_ranges: Arc<Vec<IncludedRange>>,
    limits: &'a AnalysisLimits,
}

impl<'a> ParseRequest<'a> {
    /// Creates a checked per-file parse request.
    ///
    /// # Errors
    ///
    /// Returns [`RequestError`] when source bytes or included ranges violate
    /// the explicit analysis limits.
    pub fn new(
        source: GenerationBoundSnapshot<'a>,
        language: LanguageId,
        encoding: EncodingId,
        included_ranges: Vec<IncludedRange>,
        limits: &'a AnalysisLimits,
    ) -> Result<Self, RequestError> {
        validate_request_input(&source, &included_ranges, limits)?;
        Ok(Self {
            source,
            language,
            encoding,
            included_ranges: Arc::new(included_ranges),
            limits,
        })
    }

    /// Returns the immutable generation-bound source.
    #[must_use]
    pub const fn source(&self) -> &GenerationBoundSnapshot<'a> {
        &self.source
    }

    /// Returns the requested language identity.
    #[must_use]
    pub const fn language(&self) -> &LanguageId {
        &self.language
    }

    /// Returns the declared source encoding.
    #[must_use]
    pub const fn encoding(&self) -> &EncodingId {
        &self.encoding
    }

    /// Returns sorted, disjoint embedded source ranges.
    #[must_use]
    pub fn included_ranges(&self) -> &[IncludedRange] {
        self.included_ranges.as_slice()
    }

    /// Returns shared ownership of the checked included-range identities.
    ///
    /// Parser implementations can retain this immutable owner for incremental
    /// reuse metadata without cloning language labels embedded in each range.
    #[must_use]
    pub fn shared_included_ranges(&self) -> Arc<Vec<IncludedRange>> {
        Arc::clone(&self.included_ranges)
    }

    /// Returns explicit analysis limits.
    #[must_use]
    pub const fn limits(&self) -> &AnalysisLimits {
        self.limits
    }
}

/// One bounded synchronous normalized-IR analysis request.
#[derive(Debug, Clone)]
pub struct AnalysisRequest<'a> {
    source: GenerationBoundSnapshot<'a>,
    language: LanguageId,
    encoding: EncodingId,
    included_ranges: Arc<Vec<IncludedRange>>,
    generated: Option<bool>,
    tier: AnalysisTier,
    build_context: BuildContextIdentity,
    limits: &'a AnalysisLimits,
}

impl<'a> AnalysisRequest<'a> {
    /// Creates a checked per-file analysis request.
    ///
    /// # Errors
    ///
    /// This compatibility constructor selects UTF-8 and full-file analysis.
    /// Use [`Self::new_with_parse_context`] for embedded source ranges.
    ///
    /// Returns [`RequestError`] when the immutable source violates its explicit
    /// request bound.
    pub fn new(
        source: GenerationBoundSnapshot<'a>,
        language: LanguageId,
        tier: AnalysisTier,
        build_context: BuildContextIdentity,
        limits: &'a AnalysisLimits,
    ) -> Result<Self, RequestError> {
        Self::new_with_parse_context(
            source,
            language,
            EncodingId::utf8(),
            Vec::new(),
            tier,
            build_context,
            limits,
        )
    }

    /// Creates a checked analysis request with explicit parser input context.
    ///
    /// Carrying encoding and included ranges through the analyzer boundary lets
    /// parser-backed analyzers construct an equivalent [`ParseRequest`] without
    /// weakening or duplicating request validation.
    ///
    /// # Errors
    ///
    /// Returns [`RequestError`] when source bytes or included ranges violate
    /// the explicit analysis limits.
    #[allow(clippy::too_many_arguments)]
    pub fn new_with_parse_context(
        source: GenerationBoundSnapshot<'a>,
        language: LanguageId,
        encoding: EncodingId,
        included_ranges: Vec<IncludedRange>,
        tier: AnalysisTier,
        build_context: BuildContextIdentity,
        limits: &'a AnalysisLimits,
    ) -> Result<Self, RequestError> {
        validate_request_input(&source, &included_ranges, limits)?;
        Ok(Self {
            source,
            language,
            encoding,
            included_ranges: Arc::new(included_ranges),
            generated: None,
            tier,
            build_context,
            limits,
        })
    }

    /// Records whether the source was classified as generated.
    ///
    /// Compatibility constructors intentionally leave this classification
    /// unknown. Analyzers that require it must reject the request until a
    /// caller supplies the repository-owned classification through this
    /// builder.
    #[must_use]
    pub const fn with_generated_status(mut self, generated: bool) -> Self {
        self.generated = Some(generated);
        self
    }

    /// Returns the immutable generation-bound source.
    #[must_use]
    pub const fn source(&self) -> &GenerationBoundSnapshot<'a> {
        &self.source
    }

    /// Returns the requested language identity.
    #[must_use]
    pub const fn language(&self) -> &LanguageId {
        &self.language
    }

    /// Returns the declared source encoding.
    #[must_use]
    pub const fn encoding(&self) -> &EncodingId {
        &self.encoding
    }

    /// Returns sorted, disjoint embedded source ranges.
    #[must_use]
    pub fn included_ranges(&self) -> &[IncludedRange] {
        self.included_ranges.as_slice()
    }

    /// Creates the equivalent parser request with shared range ownership.
    ///
    /// The analysis request has already validated this parser input context,
    /// so the derived request preserves it without repeating validation or
    /// cloning language labels embedded in each included range.
    #[must_use]
    pub fn to_parse_request(&self) -> ParseRequest<'a> {
        ParseRequest {
            source: self.source.clone(),
            language: self.language.clone(),
            encoding: self.encoding.clone(),
            included_ranges: Arc::clone(&self.included_ranges),
            limits: self.limits,
        }
    }

    /// Returns the repository-owned generated-source classification, if known.
    #[must_use]
    pub const fn generated_status(&self) -> Option<bool> {
        self.generated
    }

    /// Returns the requested analysis tier.
    #[must_use]
    pub const fn tier(&self) -> AnalysisTier {
        self.tier
    }

    /// Returns the build-context identity.
    #[must_use]
    pub const fn build_context(&self) -> BuildContextIdentity {
        self.build_context
    }

    /// Returns explicit analysis limits.
    #[must_use]
    pub const fn limits(&self) -> &AnalysisLimits {
        self.limits
    }
}

fn validate_request_input(
    source: &GenerationBoundSnapshot<'_>,
    ranges: &[IncludedRange],
    limits: &AnalysisLimits,
) -> Result<(), RequestError> {
    validate_source_size(source, limits)?;
    validate_included_ranges(source, ranges, limits)
}

fn validate_source_size(
    source: &GenerationBoundSnapshot<'_>,
    limits: &AnalysisLimits,
) -> Result<(), RequestError> {
    let observed = source.bytes().len();
    if observed > limits.max_source_bytes() {
        Err(RequestError::SourceTooLarge {
            observed,
            limit: limits.max_source_bytes(),
        })
    } else {
        Ok(())
    }
}

fn validate_included_ranges(
    source: &GenerationBoundSnapshot<'_>,
    ranges: &[IncludedRange],
    limits: &AnalysisLimits,
) -> Result<(), RequestError> {
    if ranges.len() > limits.max_embedded_ranges() {
        return Err(RequestError::TooManyIncludedRanges {
            observed: ranges.len(),
            limit: limits.max_embedded_ranges(),
        });
    }
    let full = source.source_ref().span();
    let mut previous_end = full.start_byte();
    for (index, range) in ranges.iter().enumerate() {
        let span = range.span();
        if span.file() != full.file()
            || span.start_byte() < full.start_byte()
            || span.end_byte() > full.end_byte()
            || span.start_byte() == span.end_byte()
        {
            return Err(RequestError::IncludedRangeOutsideSource { index });
        }
        if span.start_byte() < previous_end {
            return Err(RequestError::IncludedRangeOrder { index });
        }
        previous_end = span.end_byte();
    }
    Ok(())
}

fn validate_project_mappings(
    inputs: &[ProjectSourceInput<'_>],
    paths: &BTreeMap<&[u8], usize>,
) -> Result<(), RequestError> {
    for (input_index, input) in inputs.iter().enumerate() {
        let full = input.source.source_ref().span();
        let mut previous_end = full.start_byte();
        for (mapping_index, mapping) in input.origins.iter().enumerate() {
            let generated = mapping.generated;
            if generated.file() != full.file()
                || generated.start_byte() < full.start_byte()
                || generated.end_byte() > full.end_byte()
                || generated.start_byte() == generated.end_byte()
            {
                return Err(RequestError::GeneratedOriginOutsideSource {
                    input: input_index,
                    mapping: mapping_index,
                });
            }
            if generated.start_byte() < previous_end {
                return Err(RequestError::GeneratedOriginOrder {
                    input: input_index,
                    mapping: mapping_index,
                });
            }
            previous_end = generated.end_byte();

            if mapping.origin.start_byte() == mapping.origin.end_byte() {
                return Err(RequestError::GeneratedOriginMismatch {
                    input: input_index,
                    mapping: mapping_index,
                });
            }
            let Some(origin_index) = paths.get(mapping.origin_path.identity_bytes()) else {
                return Err(RequestError::GeneratedOriginMismatch {
                    input: input_index,
                    mapping: mapping_index,
                });
            };
            let origin = inputs
                .get(*origin_index)
                .ok_or(RequestError::ProjectAccountingOverflow)?
                .source
                .source_ref()
                .span();
            if mapping.origin.file() != origin.file()
                || mapping.origin.start_byte() < origin.start_byte()
                || mapping.origin.end_byte() > origin.end_byte()
                || mapping.origin.start_byte() == mapping.origin.end_byte()
            {
                return Err(RequestError::GeneratedOriginMismatch {
                    input: input_index,
                    mapping: mapping_index,
                });
            }
        }
    }
    Ok(())
}

fn require_project_limit(
    resource: ResourceKind,
    observed: usize,
    limit: usize,
) -> Result<(), RequestError> {
    if observed > limit {
        Err(RequestError::ProjectLimit {
            resource,
            observed,
            limit,
        })
    } else {
        Ok(())
    }
}

fn validated_project_label(
    field: LabelField,
    value: &str,
    maximum_bytes: usize,
) -> Result<String, LabelError> {
    let violation = if value.is_empty() {
        Some(LabelViolation::Empty)
    } else if value.len() > maximum_bytes {
        Some(LabelViolation::TooLong)
    } else if !value.bytes().all(|byte| {
        byte.is_ascii_alphanumeric()
            || matches!(byte, b'_' | b'-' | b'.' | b'+' | b'#' | b'/' | b':' | b'@')
    }) {
        Some(LabelViolation::InvalidByte)
    } else {
        None
    };
    match violation {
        Some(violation) => Err(LabelError { field, violation }),
        None => Ok(value.to_owned()),
    }
}
