//! Candidate-bound structural indexing, freshness, and resource evidence.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{
    performance::{ObservedDistribution, nearest_rank_distribution},
    token_accounting::sha256_hex,
};

/// Schema for structural scalability evidence.
pub const SCALABILITY_EVIDENCE_SCHEMA: &str = "rootlight.scalability-evidence/1";
/// Maximum encoded scalability evidence size.
pub const MAX_SCALABILITY_EVIDENCE_BYTES: usize = 4 * 1024 * 1024;
/// Required physical-LOC indexing throughput.
pub const MIN_STRUCTURAL_LOC_PER_SECOND: u64 = 120_000;
/// Maximum process-tree RSS for the ten-million-LOC fixture.
pub const MAX_TEN_MILLION_LOC_RSS_BYTES: u64 = 2 * 1024 * 1024 * 1024;
/// Maximum structural index size as parts per million of checked-out source.
pub const MAX_STRUCTURAL_INDEX_SIZE_PPM: u64 = 350_000;
/// Maximum non-source durable state as parts per million of checked-out source.
pub const MAX_DURABLE_NON_SOURCE_SIZE_PPM: u64 = 600_000;
/// Fixed durable control-plane allowance beyond source-derived state.
pub const DURABLE_CONTROL_OVERHEAD_BYTES: u64 = 64 * 1024 * 1024;

const REQUIRED_COLD_INDEX_ATTEMPTS: usize = 5;
const REQUIRED_FRESHNESS_SAMPLES: usize = 100;
const ONE_FILE_FRESHNESS_P95_NS: u64 = 500_000_000;
const TEN_FILE_FRESHNESS_P95_NS: u64 = 2_000_000_000;
const HUNDRED_FILE_FRESHNESS_P95_NS: u64 = 10_000_000_000;

/// Closed source-size class used by a scalability fixture.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScalabilityClass {
    /// One million through ten million physical source lines.
    Large,
}

/// Final disposition derived from every mandatory scalability threshold.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScalabilityDisposition {
    /// Every mandatory observation exists and passes.
    Pass,
}

/// Exact candidate and reference-host identity.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ScalabilityEnvironment {
    /// Exact lowercase Git object ID.
    pub source_revision: String,
    /// Rust target triple of the measured binaries.
    pub target_triple: String,
    /// Operating-system family.
    pub operating_system: String,
    /// CPU architecture.
    pub architecture: String,
    /// Source-free CPU model identifier.
    pub cpu_model: String,
    /// Available logical processors.
    pub cpu_count: u32,
    /// Installed or constrained memory.
    pub memory_bytes: u64,
    /// Cargo profile of the measured binaries.
    pub build_profile: String,
    /// Exact release binary digests.
    pub binary_sha256: BTreeMap<String, String>,
}

/// Deterministic source fixture identity and composition.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ScalabilityFixture {
    /// Stable fixture identifier.
    pub fixture_id: String,
    /// Closed source-size class.
    pub scale_class: ScalabilityClass,
    /// Digest over ordered paths and exact contents.
    pub fixture_sha256: String,
    /// Included regular source files.
    pub source_files: u64,
    /// Included source bytes.
    pub source_bytes: u64,
    /// Included non-empty physical source lines.
    pub physical_loc: u64,
    /// Generated bytes admitted into the source scope.
    pub generated_bytes: u64,
    /// Bytes excluded from the source scope.
    pub excluded_bytes: u64,
    /// Physical source lines by language.
    pub language_loc: BTreeMap<String, u64>,
}

/// Normalized generation counts read from the sealed structural oracle.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StructuralFactCounts {
    /// Indexed files.
    pub files: u64,
    /// Semantic entities.
    pub entities: u64,
    /// Source occurrences.
    pub occurrences: u64,
    /// Typed relations.
    pub relations: u64,
    /// Total retained normalized facts.
    pub total_facts: u64,
}

/// Throughput distributions derived from the same cold-index attempts.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StructuralThroughput {
    /// Physical source lines per second.
    pub physical_loc_per_second: ObservedDistribution,
    /// Source bytes per second.
    pub source_bytes_per_second: ObservedDistribution,
    /// Files per second.
    pub files_per_second: ObservedDistribution,
    /// Entities per second.
    pub entities_per_second: ObservedDistribution,
    /// Occurrences per second.
    pub occurrences_per_second: ObservedDistribution,
    /// Relations per second.
    pub relations_per_second: ObservedDistribution,
    /// Total normalized facts per second.
    pub total_facts_per_second: ObservedDistribution,
}

/// Repeated cold structural-index measurements.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ColdIndexEvidence {
    /// Exact measured fixture.
    pub fixture: ScalabilityFixture,
    /// Raw monotonic attempt durations.
    pub elapsed_ns_samples: Vec<u64>,
    /// Derived latency distribution.
    pub elapsed_ns: ObservedDistribution,
    /// Stable fact counts observed in every attempt.
    pub facts: StructuralFactCounts,
    /// Derived indexing rates.
    pub throughput: StructuralThroughput,
}

/// One 100-sample incremental freshness distribution.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FreshnessEvidence {
    /// Ordinary body-edited files per generation.
    pub changed_files: u32,
    /// Raw edit-to-durable-publication durations.
    pub elapsed_ns_samples: Vec<u64>,
    /// Derived latency distribution.
    pub elapsed_ns: ObservedDistribution,
    /// Fixed inclusive p95 limit.
    pub p95_limit_ns: u64,
}

/// Ten-million-LOC structural resource observation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StructuralResourceEvidence {
    /// Exact measured fixture.
    pub fixture: ScalabilityFixture,
    /// End-to-end cold indexing time.
    pub elapsed_ns: u64,
    /// Fact counts from the sealed generation.
    pub facts: StructuralFactCounts,
    /// Peak daemon plus MCP process-tree RSS.
    pub process_tree_peak_rss_bytes: u64,
    /// Fixed inclusive RSS limit.
    pub rss_limit_bytes: u64,
    /// Durable structural state bytes after publication.
    pub structural_index_bytes: u64,
    /// Structural state size divided by checked-out source bytes.
    pub structural_index_size_ppm: u64,
    /// Fixed inclusive structural-index ratio.
    pub structural_index_size_limit_ppm: u64,
    /// Compressed or exact generation-pinned source snapshot bytes.
    pub durable_snapshot_bytes: u64,
    /// Complete durable state bytes, including snapshots and control metadata.
    pub durable_total_bytes: u64,
    /// Inclusive source-derived bound for complete durable state.
    pub durable_total_bound_bytes: u64,
    /// Peak bytes observed in operation-owned staging directories.
    pub temporary_peak_bytes: u64,
    /// Predeclared inclusive temporary-space bound.
    pub temporary_bound_bytes: u64,
    /// Staging bytes remaining after successful publication.
    pub temporary_residual_bytes: u64,
    /// Whether all operation-owned temporary data was reclaimed.
    pub temporary_reclaimed: bool,
}

/// Complete candidate-bound scalability evidence.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ScalabilityEvidence {
    /// Evidence schema.
    pub schema: String,
    /// Candidate and host identity.
    pub environment: ScalabilityEnvironment,
    /// Five independent one-million-LOC cold index attempts.
    pub cold_index: ColdIndexEvidence,
    /// One-, ten-, and hundred-file freshness distributions.
    pub freshness: Vec<FreshnessEvidence>,
    /// Ten-million-LOC memory, disk, and temporary-space observation.
    pub ten_million_loc_resources: StructuralResourceEvidence,
    /// Derived all-threshold disposition.
    pub disposition: ScalabilityDisposition,
}

impl ScalabilityEvidence {
    /// Validates identities, denominators, derivations, and fixed thresholds.
    ///
    /// # Errors
    ///
    /// Returns [`ScalabilityEvidenceError`] for malformed or failing evidence.
    pub fn validate(&self) -> Result<(), ScalabilityEvidenceError> {
        if self.schema != SCALABILITY_EVIDENCE_SCHEMA
            || !is_git_revision(&self.environment.source_revision)
            || self.environment.target_triple.is_empty()
            || self.environment.operating_system.is_empty()
            || self.environment.architecture.is_empty()
            || self.environment.cpu_model.is_empty()
            || self.environment.cpu_count == 0
            || self.environment.memory_bytes == 0
            || self.environment.build_profile != "release"
            || self.environment.binary_sha256.len() != 2
            || !self.environment.binary_sha256.iter().all(|(name, digest)| {
                matches!(name.as_str(), "rootlight-daemon" | "rootlight-mcp") && is_sha256(digest)
            })
        {
            return Err(ScalabilityEvidenceError::InvalidEnvironment);
        }
        validate_fixture(&self.cold_index.fixture, 1_000_000)?;
        if self.cold_index.elapsed_ns_samples.len() != REQUIRED_COLD_INDEX_ATTEMPTS
            || distribution(&self.cold_index.elapsed_ns_samples)? != self.cold_index.elapsed_ns
        {
            return Err(ScalabilityEvidenceError::InvalidColdIndex);
        }
        validate_fact_counts(&self.cold_index.facts, &self.cold_index.fixture)?;
        validate_throughput(&self.cold_index)?;
        if self.cold_index.throughput.physical_loc_per_second.p50 < MIN_STRUCTURAL_LOC_PER_SECOND {
            return Err(ScalabilityEvidenceError::ColdIndexThreshold);
        }
        validate_freshness(&self.freshness)?;

        let resources = &self.ten_million_loc_resources;
        validate_fixture(&resources.fixture, 10_000_000)?;
        validate_fact_counts(&resources.facts, &resources.fixture)?;
        let expected_ratio = ratio_ppm(
            resources.structural_index_bytes,
            resources.fixture.source_bytes,
        )?;
        let expected_durable_bound = structural_durable_total_bound(
            resources.fixture.source_bytes,
            resources.durable_snapshot_bytes,
        )?;
        if resources.elapsed_ns == 0
            || resources.process_tree_peak_rss_bytes == 0
            || resources.rss_limit_bytes != MAX_TEN_MILLION_LOC_RSS_BYTES
            || resources.process_tree_peak_rss_bytes > resources.rss_limit_bytes
            || resources.structural_index_size_limit_ppm != MAX_STRUCTURAL_INDEX_SIZE_PPM
            || resources.structural_index_size_ppm != expected_ratio
            || resources.structural_index_size_ppm > resources.structural_index_size_limit_ppm
            || resources.durable_total_bytes < resources.structural_index_bytes
            || resources.durable_total_bytes < resources.durable_snapshot_bytes
            || resources.durable_total_bound_bytes != expected_durable_bound
            || resources.durable_total_bytes > resources.durable_total_bound_bytes
            || resources.temporary_bound_bytes == 0
            || resources.temporary_peak_bytes > resources.temporary_bound_bytes
            || resources.temporary_residual_bytes != 0
            || !resources.temporary_reclaimed
        {
            return Err(ScalabilityEvidenceError::ResourceThreshold);
        }
        if self.disposition != ScalabilityDisposition::Pass {
            return Err(ScalabilityEvidenceError::InvalidDisposition);
        }
        Ok(())
    }
}

/// Encodes one validated scalability evidence package.
///
/// # Errors
///
/// Returns [`ScalabilityEvidenceError`] when validation, serialization, or the
/// byte ceiling fails.
pub fn encode_scalability_evidence(
    evidence: &ScalabilityEvidence,
) -> Result<Vec<u8>, ScalabilityEvidenceError> {
    evidence.validate()?;
    let encoded =
        serde_json::to_vec(evidence).map_err(|_| ScalabilityEvidenceError::Serialization)?;
    if encoded.len() > MAX_SCALABILITY_EVIDENCE_BYTES {
        return Err(ScalabilityEvidenceError::TooLarge);
    }
    Ok(encoded)
}

/// Decodes and validates a bounded scalability evidence package.
///
/// # Errors
///
/// Returns [`ScalabilityEvidenceError`] for oversized, malformed, or failing
/// evidence.
pub fn decode_scalability_evidence(
    encoded: &[u8],
) -> Result<ScalabilityEvidence, ScalabilityEvidenceError> {
    if encoded.len() > MAX_SCALABILITY_EVIDENCE_BYTES {
        return Err(ScalabilityEvidenceError::TooLarge);
    }
    let evidence = serde_json::from_slice::<ScalabilityEvidence>(encoded)
        .map_err(|_| ScalabilityEvidenceError::InvalidEncoding)?;
    evidence.validate()?;
    Ok(evidence)
}

/// Returns the SHA-256 of canonical encoded scalability evidence.
///
/// # Errors
///
/// Returns [`ScalabilityEvidenceError`] when the evidence is invalid.
pub fn scalability_evidence_sha256(
    evidence: &ScalabilityEvidence,
) -> Result<String, ScalabilityEvidenceError> {
    Ok(sha256_hex(&encode_scalability_evidence(evidence)?))
}

/// Derives nearest-rank latency or throughput percentiles.
///
/// # Errors
///
/// Returns [`ScalabilityEvidenceError`] for an empty sample set.
pub fn scalability_distribution(
    samples: &[u64],
) -> Result<ObservedDistribution, ScalabilityEvidenceError> {
    distribution(samples)
}

/// Derives the complete durable-state ceiling from source and snapshot bytes.
///
/// The source snapshot is accounted exactly. Structural and control state may
/// consume at most sixty percent of checked-out source plus a fixed allowance.
///
/// # Errors
///
/// Returns [`ScalabilityEvidenceError::CounterOverflow`] when the bound cannot
/// be represented.
pub fn structural_durable_total_bound(
    source_bytes: u64,
    durable_snapshot_bytes: u64,
) -> Result<u64, ScalabilityEvidenceError> {
    let variable_non_source = source_bytes
        .checked_mul(MAX_DURABLE_NON_SOURCE_SIZE_PPM)
        .ok_or(ScalabilityEvidenceError::CounterOverflow)?
        / 1_000_000;
    durable_snapshot_bytes
        .checked_add(variable_non_source)
        .and_then(|value| value.checked_add(DURABLE_CONTROL_OVERHEAD_BYTES))
        .ok_or(ScalabilityEvidenceError::CounterOverflow)
}

fn validate_fixture(
    fixture: &ScalabilityFixture,
    expected_loc: u64,
) -> Result<(), ScalabilityEvidenceError> {
    let language_loc = fixture
        .language_loc
        .values()
        .try_fold(0_u64, |sum, value| sum.checked_add(*value))
        .ok_or(ScalabilityEvidenceError::CounterOverflow)?;
    if fixture.fixture_id.is_empty()
        || !is_sha256(&fixture.fixture_sha256)
        || fixture.scale_class != ScalabilityClass::Large
        || fixture.source_files == 0
        || fixture.source_bytes == 0
        || fixture.physical_loc != expected_loc
        || language_loc != fixture.physical_loc
        || fixture.generated_bytes != 0
        || fixture.excluded_bytes != 0
        || fixture.language_loc.keys().any(String::is_empty)
    {
        return Err(ScalabilityEvidenceError::InvalidFixture);
    }
    Ok(())
}

fn validate_fact_counts(
    facts: &StructuralFactCounts,
    fixture: &ScalabilityFixture,
) -> Result<(), ScalabilityEvidenceError> {
    let total = facts
        .entities
        .checked_add(facts.occurrences)
        .and_then(|value| value.checked_add(facts.relations))
        .ok_or(ScalabilityEvidenceError::CounterOverflow)?;
    if facts.files != fixture.source_files
        || facts.entities == 0
        || facts.total_facts != total
        || facts.total_facts == 0
    {
        return Err(ScalabilityEvidenceError::InvalidFactCounts);
    }
    Ok(())
}

fn validate_throughput(evidence: &ColdIndexEvidence) -> Result<(), ScalabilityEvidenceError> {
    let fixture = &evidence.fixture;
    let facts = evidence.facts;
    for (observed, numerator) in [
        (
            &evidence.throughput.physical_loc_per_second,
            fixture.physical_loc,
        ),
        (
            &evidence.throughput.source_bytes_per_second,
            fixture.source_bytes,
        ),
        (&evidence.throughput.files_per_second, facts.files),
        (&evidence.throughput.entities_per_second, facts.entities),
        (
            &evidence.throughput.occurrences_per_second,
            facts.occurrences,
        ),
        (&evidence.throughput.relations_per_second, facts.relations),
        (
            &evidence.throughput.total_facts_per_second,
            facts.total_facts,
        ),
    ] {
        let samples = rates(numerator, &evidence.elapsed_ns_samples)?;
        if distribution(&samples)? != *observed {
            return Err(ScalabilityEvidenceError::InvalidColdIndex);
        }
    }
    Ok(())
}

fn validate_freshness(freshness: &[FreshnessEvidence]) -> Result<(), ScalabilityEvidenceError> {
    if freshness.len() != 3 {
        return Err(ScalabilityEvidenceError::InvalidFreshness);
    }
    for (observed, (changed_files, limit)) in freshness.iter().zip([
        (1, ONE_FILE_FRESHNESS_P95_NS),
        (10, TEN_FILE_FRESHNESS_P95_NS),
        (100, HUNDRED_FILE_FRESHNESS_P95_NS),
    ]) {
        if observed.changed_files != changed_files
            || observed.elapsed_ns_samples.len() != REQUIRED_FRESHNESS_SAMPLES
            || observed.p95_limit_ns != limit
            || distribution(&observed.elapsed_ns_samples)? != observed.elapsed_ns
            || observed.elapsed_ns.p95 > limit
        {
            return Err(ScalabilityEvidenceError::FreshnessThreshold);
        }
    }
    Ok(())
}

fn distribution(samples: &[u64]) -> Result<ObservedDistribution, ScalabilityEvidenceError> {
    nearest_rank_distribution(samples).map_err(|_| ScalabilityEvidenceError::EmptyDistribution)
}

fn rates(numerator: u64, elapsed_ns_samples: &[u64]) -> Result<Vec<u64>, ScalabilityEvidenceError> {
    elapsed_ns_samples
        .iter()
        .map(|elapsed| {
            if *elapsed == 0 {
                return Err(ScalabilityEvidenceError::InvalidColdIndex);
            }
            numerator
                .checked_mul(1_000_000_000)
                .ok_or(ScalabilityEvidenceError::CounterOverflow)
                .map(|scaled| scaled / elapsed)
        })
        .collect()
}

fn ratio_ppm(numerator: u64, denominator: u64) -> Result<u64, ScalabilityEvidenceError> {
    if denominator == 0 {
        return Err(ScalabilityEvidenceError::CounterOverflow);
    }
    numerator
        .checked_mul(1_000_000)
        .ok_or(ScalabilityEvidenceError::CounterOverflow)
        .map(|scaled| scaled / denominator)
}

fn is_git_revision(value: &str) -> bool {
    value.len() == 40 && is_lower_hex(value)
}

fn is_sha256(value: &str) -> bool {
    value.len() == 64 && is_lower_hex(value)
}

fn is_lower_hex(value: &str) -> bool {
    value
        .bytes()
        .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

/// Validation failure for structural scalability evidence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum ScalabilityEvidenceError {
    /// Candidate or host identity is invalid.
    #[error("scalability environment is invalid")]
    InvalidEnvironment,
    /// A fixture identity or composition is invalid.
    #[error("scalability fixture is invalid")]
    InvalidFixture,
    /// Cold-index samples or their derivations are invalid.
    #[error("cold-index evidence is invalid")]
    InvalidColdIndex,
    /// Cold structural indexing missed its fixed throughput target.
    #[error("cold-index throughput is below the product threshold")]
    ColdIndexThreshold,
    /// Sealed normalized fact counts are inconsistent.
    #[error("structural fact counts are invalid")]
    InvalidFactCounts,
    /// Freshness distributions are missing or malformed.
    #[error("freshness evidence is invalid")]
    InvalidFreshness,
    /// A freshness distribution missed its fixed p95 limit.
    #[error("incremental freshness exceeds the product threshold")]
    FreshnessThreshold,
    /// Ten-million-LOC resource evidence missed a fixed limit.
    #[error("structural resource evidence exceeds the product threshold")]
    ResourceThreshold,
    /// The final disposition is inconsistent.
    #[error("scalability disposition is invalid")]
    InvalidDisposition,
    /// A derived counter overflowed.
    #[error("scalability counter overflow")]
    CounterOverflow,
    /// A required percentile distribution is empty.
    #[error("scalability distribution is empty")]
    EmptyDistribution,
    /// Serialization failed.
    #[error("scalability evidence serialization failed")]
    Serialization,
    /// Encoded evidence exceeds its byte ceiling.
    #[error("scalability evidence exceeds its byte ceiling")]
    TooLarge,
    /// Encoded evidence is malformed.
    #[error("scalability evidence encoding is invalid")]
    InvalidEncoding,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixed_threshold_constants_match_the_public_product_contract() {
        assert_eq!(MIN_STRUCTURAL_LOC_PER_SECOND, 120_000);
        assert_eq!(MAX_TEN_MILLION_LOC_RSS_BYTES, 2_147_483_648);
        assert_eq!(MAX_STRUCTURAL_INDEX_SIZE_PPM, 350_000);
        assert_eq!(MAX_DURABLE_NON_SOURCE_SIZE_PPM, 600_000);
        assert_eq!(DURABLE_CONTROL_OVERHEAD_BYTES, 67_108_864);
        assert_eq!(ONE_FILE_FRESHNESS_P95_NS, 500_000_000);
        assert_eq!(TEN_FILE_FRESHNESS_P95_NS, 2_000_000_000);
        assert_eq!(HUNDRED_FILE_FRESHNESS_P95_NS, 10_000_000_000);
    }

    #[test]
    fn distribution_uses_nearest_rank_percentiles() {
        let samples = (1..=100).collect::<Vec<_>>();
        let observed = scalability_distribution(&samples).expect("distribution is available");

        assert_eq!(observed.p50, 50);
        assert_eq!(observed.p95, 95);
        assert_eq!(observed.p99, 99);
    }

    #[test]
    fn durable_total_bound_accounts_for_snapshot_ratio_and_control_state() {
        assert_eq!(
            structural_durable_total_bound(1_000_000, 750_000)
                .expect("fixture bound is representable"),
            68_458_864
        );
    }
}
